import random

quotes = {
    0: ["If u wanna get something done right, do it yourself", " You're right, Elias, I'm not a Ghost... I'm the man that hunts them, and sends them back to the other side!", " Look at what you did. [Rorke kicks Hesh] You're good. You would have been a hell of a Ghost. But that's not gonna happen. There ain't gonna be any Ghosts... We're gonna destroy them together.", " Everyone breaks, Elias!", " Shit, son.", " You know our laws, son. You fail to protect your brothers...you join them in death.", " I am Gabriel Rorke. I have been trained by your Government to be a weapon. Trained to kill and destroy. All in the name of Liberty and Justice. Even surrender my very life in service to your country. But I am not one of you. The \"Just\" have turned their backs and become deaf to your cries. Who, then will show them justice? Who will show you the Liberty they have promised? The weapon they have created will be their undoing. But do not fear this. Do not fear me. It is only natural. Like the collapse of Rome, your cities will crumble and there will be great sorrow. But from the ashes of this diseased metropolis, a rebirth will occur. It will be paid for in blood and steel. Liberty must be restored. I am Gabriel Rorke, and I am here to show you the true meaning of justice.", " What's the matter? You look like you've just seen a ghost.", "Time to work, soldiers."],
    1: [" The healthy human mind doesn't wake up in the morning thinking that this is its last day on earth. But I think that's a luxury, not a curse. Knowing you're close to the end is a kind of freedom. Good time to take... inventory. Outgunned. Outnumbered. Out of our minds. On a suicide mission. But the sand and rocks here stained with thousands of years of warfare, they will remember us. For this. Because out of all our vast array of nightmares, this is the one we choose for ourselves. We go forward like a breath exhaled from the Earth. With vigor in our hearts and one goal in sight: We. Will. Kill him.", " Right… What the hell kind of name is Soap, eh? How'd a muppet like you pass Selection?", " The package is aboard a medium freighter. Estonian registration number 52775. There is a small crew and security detail onboard.", " Nikolai's in hell right now, we're gonna walk him out. We take care of our friends. Let's move.", " All right. Let's top these bastards before they kill the old man.", " Why'd you do it? Where did you get the bomb?", " Zakhaev's son, commander of the Ultranationalist forces in the field. Rotten apple doesn't fall far from the tree. The Loyalist, Kamarov, has got a location on the kid.", " They've started a bloody countdown! Zakhaev's gonna launch the remaining missiles!", " Well at least the world didn't end. Hit it.", " Roger that Soap. I've found Roach. He appears to be intact.", " Do NOT trust Shepherd- I say again, DO NOT TRUST SHEPHERD! Soap! GET DOWN!", " Makarov wouldn't let this travel lightly if it didn't serve a greater purpose, and chances are the bastard will be there personally to see things off. If he's back on the grid...then so are we", " Soap TRUSTED you. I thought I could too. So WHY, IN BLOODY HELL, DOES MAKAROV KNOW YOU?!", " We're gonna have one shot to grab the President before he gives up the launch codes and Makarov turns Europe into glass. Once we get boots on the ground, it's going to get lively down there.", " Prisoner 627. I'm coming for you, Makarov.", " My war ends with you.", " You wouldn't have to look far"],
    2: ["This is it... Ready to make history?", "No, no, no, somethin's wrong. There's way too much activity.", "FUUUUUUUCK!", "Kravchenko. When I sliced that bastard open, it saved everyone's ass. But he comes to first, BOOM! Welcome to the Hanoi Hilton. Six months later, they shipped me over to Da Nang. And this fucking place made the Hilton look good. We lost 17 in my group. By '72, it was just me. I was not gonna die in a FUCKING SWAMP!!", "Thanks to your old man. He put it all on the line for me... for honor... and friendship."],
    3: [" Come my friends. 'Tis not too late to seek a newer world.", " Martyr me...for Cordis Die.", " Victory is not measured by losses Farid(_shoots a chopper with FMJ_), its measured by gains", " It matters not, I am one step ahead of him", " We will regroup at the citadel", " I DECIDE WHAT IS NECESSARY!", " Your life will be consumed by absolute losses, then and only then you will understand what you have done to me.", " You suffer with me!"],
    4: ["You did it, Mason! You did what I could not!", "The men and I had fought through the most bitter of winters on the Eastern Front, but we were no strangers to the cold. Even now, the blood in my veins chills when I think back to the events of that day... Far, far from home...", "Today, my comrades... Vorkuta... BURNS!!!", "Die like the RATS you are"]
}

def choice():
    ch1 = random.randint(0,4)
    return (quotes[ch1][random.randint(0, len(quotes[ch1]) - 1)])